/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModels.HDCT;
import DomainModels.HangSanXuat;
import DomainModels.HoaDon;
import DomainModels.KhachHang;
import DomainModels.NhanVien;
import DomainModels.SanPham;
import DomainModels.TheLoaiSanPham;
import Service.HDCTService;
import Service.HoaDonService;
import Service.KhachHangService;
import Service.NhanVienService;
import Service.SanPhamService;
import ViewModels.HDCTView;
import ViewModels.HoaDonView;
import ViewModels.SanPhamView;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Utilities;
import Ultilities.Ulti;
import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class HoaDonPannel extends javax.swing.JPanel {

    SanPhamService sanPhamService;
    HoaDonService hoaDonService;
    NhanVienService nhanVienService;
    KhachHangService khachHangService;
    HDCTService hDCTService;
    Ulti _Utilities;

    /**
     * Creates new form HoaDonPannel
     */
    private String user;
    public HoaDonPannel(String user) {
        initComponents();
        sanPhamService = new SanPhamService();
        hoaDonService = new HoaDonService();
        nhanVienService = new NhanVienService();
        khachHangService = new KhachHangService();
        hDCTService = new HDCTService();
        _Utilities = new Ulti();
        this.user = user;
      //  cbcNhanVien(nhanVienService.listNhanVien());
       // cbcKhachHang(khachHangService.lishKH());
        loadTableSanPham(sanPhamService.listSanPham());
        loadtableHoaDon(hoaDonService.getList());
        loadTableKhachHang(khachHangService.lishKH());
       loadtableHoaDon1(hoaDonService.getListThanhToan());
        //   loadTableGioHang(hDCTService.getList());
        //txt_tongtien.setText(String.valueOf(inHoaDon()));
//        txt_tongtien.setEnabled(false);
//        txt_tienthua.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_hoadon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txt_tienkhachdua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txt_tongtien = new javax.swing.JLabel();
        txt_tienthua = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_giohang = new javax.swing.JTable();
        btn_tra = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        btn_Timkiem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_sanPham = new javax.swing.JTable();
        txt_soluong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        rdb_Gia1 = new javax.swing.JRadioButton();
        rdb_Gia2 = new javax.swing.JRadioButton();
        rdb_Gia3 = new javax.swing.JRadioButton();
        btn_taohoadon = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_khachhang = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_hoadon1 = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mua Bán Pob"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));

        tb_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Ngày Tạo", "Mã Khách Hàng", "Mã Người Tạo", "Trang thái"
            }
        ));
        tb_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_hoadon);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tính Tiền"));

        jLabel1.setText("Tổng tiền");

        jLabel2.setText("Tiền khách đưa");

        jLabel3.setText("Tiền thừa");

        jButton2.setText("Thanh Toán");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Làm mới");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txt_tongtien.setText("--");

        txt_tienthua.setText("--");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(txt_tienthua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tongtien))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tienthua))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ Hàng"));

        tb_giohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "Mã HĐ", "Số Lượng", "Đơn Giá", "Tổng Tiền"
            }
        ));
        tb_giohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_giohangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_giohang);

        btn_tra.setText("Trả");
        btn_tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btn_tra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tra)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm"));

        btn_Timkiem.setText("Tìm Kiếm");
        btn_Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimkiemActionPerformed(evt);
            }
        });

        tb_sanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên SP", "Số Lượng Tồn", "Hãng SX", "Năm SX", "Giá Bán", "Dung tích", "Pin", "Mô tả"
            }
        ));
        tb_sanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_sanPham);

        jLabel4.setText("Số Lượng");

        jButton5.setText("Thêm vào giỏ hàng");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdb_Gia1);
        rdb_Gia1.setText("Giá (0-500k)");
        rdb_Gia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Gia1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdb_Gia2);
        rdb_Gia2.setText("Giá (500k - 1tr)");
        rdb_Gia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Gia2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdb_Gia3);
        rdb_Gia3.setText("Giá (1 - 2tr)");
        rdb_Gia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Gia3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rdb_Gia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdb_Gia2))
                            .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_Timkiem)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(rdb_Gia3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Timkiem)
                    .addComponent(jLabel4)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_Gia1)
                    .addComponent(rdb_Gia2)
                    .addComponent(rdb_Gia3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_taohoadon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_taohoadon.setText("Tạo Hóa Đơn");
        btn_taohoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taohoadonActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách Hàng"));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Khách Hàng", "Giới Tính", "Email", "SĐT"
            }
        ));
        jScrollPane4.setViewportView(tbl_khachhang);

        jButton1.setText("Thêm khách hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tìm kiếm khách hàng");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txt_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jButton1))
                .addGap(87, 87, 87))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));

        tb_hoadon1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Ngày Tạo", "Mã Khách Hàng", "Mã Người Tạo", "Trang thái"
            }
        ));
        tb_hoadon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hoadon1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tb_hoadon1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_taohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_taohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public float inHoaDon() {
        int index = tb_hoadon.getSelectedRow();
        HoaDon hd = hoaDonService.getList().get(index);
        int maHD = hd.getMaHoaDon();
        List<HDCT> list = hDCTService.timKiem(maHD);
        
        float tong = 0;
        for (HDCT x : list) {
            tong+=x.getTongTien();
        }
        return tong;
    }

    public void cbcNhanVien(List<NhanVien> nv) {
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel();
        for (NhanVien x : nv) {
            boxModel.addElement(x.getMaNhanVien());
        }
        //  cbc_nv.setModel(boxModel);
    }

//    public void cbcKhachHang(List<KhachHang> kh) {
//        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
//        for (KhachHang x : kh) {
//            dcbm.addElement(x.getMaKhachHang());
//        }
//        cbc_kh.setModel(dcbm);
//    }
    public void loadTableKhachHang(List<KhachHang> kh){
        DefaultTableModel tableModelkh = new DefaultTableModel();
        tableModelkh = (DefaultTableModel) tbl_khachhang.getModel();
        tableModelkh.setRowCount(0);
        for (KhachHang x : kh) {
            tableModelkh.addRow(new Object[]{x.getTenKhachHang(),x.getGioiTinh(),x.getEmail(),x.getSDT()});
        }
    }

    public void loadTableSanPham(List<SanPham> sp) {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel = (DefaultTableModel) tb_sanPham.getModel();
        defaultTableModel.setRowCount(0);
        int stt = 1;
        for (SanPham x : sp) {
            defaultTableModel.addRow(new Object[]{stt++, x.getMaSanPham(), x.getTenSanPham(), x.getSoLuong(), x.getMaHangSX().getTenHang(), x.getNamSanXuat(),
                 x.getGiaBan(), x.getDungTich(), x.getPin(), x.getMoTa()});
        }
    }
    

    public void loadtableHoaDon(List<HoaDon> hd) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel = (DefaultTableModel) tb_hoadon.getModel();
        tableModel.setRowCount(0);
        int stt = 1;
        for (HoaDon x : hd) {
            tableModel.addRow(new Object[]{stt++, x.getMaHoaDon(), x.getNgayTao(), 
                x.getMaKhachHang().getMaKhachHang(), x.getMaNhanVien().getMaNhanVien(),x.getTrangThai()==0?"Chưa thanh toán":"Đã thanh toán"});
        }
    }
    public void loadtableHoaDon1(List<HoaDon> hd) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel = (DefaultTableModel) tb_hoadon1.getModel();
        tableModel.setRowCount(0);
        int stt = 1;
        for (HoaDon x : hd) {
            tableModel.addRow(new Object[]{stt++, x.getMaHoaDon(), x.getNgayTao(), 
                x.getMaKhachHang().getMaKhachHang(), x.getMaNhanVien().getMaNhanVien(),x.getTrangThai()==0?"Chưa thanh toán":"Đã thanh toán"});
        }
    }

    public void loadTableGioHang(List<HDCT> ct) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tb_giohang.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (HDCT x : ct) {
            model.addRow(new Object[]{stt++, getTensp(x.getMaSanPham().getMaSanPham()), x.getMaHoaDon().getMaHoaDon(), x.getSoLuong(), x.getDonGia(), x.getTongTien()});
        }
    }
     public String getTensp(String ma){
      //  List<SanPham> _list =new ArrayList<>();
        for (SanPham x : sanPhamService.listSanPham()) {
            if (x.getMaSanPham().equals(ma)) {
               return x.getTenSanPham();
            }
        }
        return null;
    }
   public String getIdsp(String ten){
      //  List<SanPham> _list =new ArrayList<>();
        for (SanPham x : sanPhamService.listSanPham()) {
            if (x.getTenSanPham().equals(ten)) {
               return x.getMaSanPham();
            }
        }
        return null;
    }

    HoaDonView guiDataHoaDon() {
        int ma = 0;
        for (int i = 0; i < hoaDonService.getList().size(); i++) {
            ma++;
        }
        int index = tbl_khachhang.getSelectedRow();
        KhachHang kh = (KhachHang) khachHangService.timKiem(txt_khachhang.getText()).get(index);
        int maKhachHang = kh.getMaKhachHang();
        Date date = new Date();
        KhachHang khachHang = new KhachHang(maKhachHang, "", 0, "", "");
        NhanVien nhanVien = new NhanVien(user, "", "", date, 0, "", "", "", 0, 0);
        return new HoaDonView(-1, date, khachHang, nhanVien,0);
    }
    HoaDonView guiDataThanhToan(){
        int index = tb_hoadon.getSelectedRow();
        HoaDon hd = hoaDonService.getList().get(index);
        Date date = new Date();
        KhachHang khachHang = new KhachHang(hd.getMaKhachHang().getMaKhachHang(), "", 0, "", "");
        NhanVien nhanVien = new NhanVien(user, "", "", date, 0, "", "", "", 0, 0);
        return new HoaDonView(hd.getMaHoaDon(), hd.getNgayTao(), khachHang, nhanVien, 1);
    }

    HDCTView guidataHDCT() {
        int soLuong = Integer.parseInt(txt_soluong.getText());
        Date date = new Date();
        int indexHoaDon = tb_hoadon.getSelectedRow();
        HoaDon hd = hoaDonService.getList().get(indexHoaDon);
        int maHoaDon = hd.getMaHoaDon();
        int indexSanPham = tb_sanPham.getSelectedRow();
        SanPham sp = sanPhamService.listSanPham().get(indexSanPham);
        String maSanPham = sp.getMaSanPham();
        Float donGia = sp.getGiaBan();
        TheLoaiSanPham loaiSanPham = new TheLoaiSanPham();
        HangSanXuat hangSanXuat = new HangSanXuat();
        KhachHang khachHang = new KhachHang();
        NhanVien nhanVien = new NhanVien();
        HoaDon hoaDon = new HoaDon(maHoaDon, date, khachHang, nhanVien,0);
        SanPham sanPham = new SanPham(maSanPham, "", 1, date, "", 1, 1, 1, "", "", "","","",0, loaiSanPham, hangSanXuat);
        return new HDCTView(-1, donGia, soLuong, (donGia * soLuong), hoaDon, sanPham);
    }
    

    public List<SanPham> timKiem(String ma) {
        List<SanPham> lst = new ArrayList<>();
        for (SanPham x : sanPhamService.listSanPham()) {
            if (x.getMaSanPham().equalsIgnoreCase(ma) || x.getTenSanPham().startsWith(ma)) {
                lst.add(x);
            }
        }
        return lst;
    }

    //Tìm theo giá
    public List<SanPham> timKiemGia1() {
        List<SanPham> lst = new ArrayList<>();
        for (SanPham x : sanPhamService.listSanPham()) {
            if (x.getGiaBan() >= 0 && x.getGiaBan() <= 500000) {
                lst.add(x);
            }
        }
        return lst;
    }

    public List<SanPham> timKiemGia2() {
        List<SanPham> lst = new ArrayList<>();
        for (SanPham x : sanPhamService.listSanPham()) {
            if (x.getGiaBan() > 500000 && x.getGiaBan() <= 1000000) {
                lst.add(x);
            }
        }
        return lst;
    }

    public List<SanPham> timKiemGia3() {
        List<SanPham> lst = new ArrayList<>();
        for (SanPham x : sanPhamService.listSanPham()) {
            if (x.getGiaBan() > 1000000 && x.getGiaBan() <= 2000000) {
                lst.add(x);
            }
        }
        return lst;
    }


    private void btn_taohoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taohoadonActionPerformed
        JOptionPane.showMessageDialog(this, hoaDonService.add(guiDataHoaDon()));
        loadtableHoaDon(hoaDonService.getList());
    }//GEN-LAST:event_btn_taohoadonActionPerformed

    private void tb_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hoadonMouseClicked
        int index = tb_hoadon.getSelectedRow();
        HoaDon hd = hoaDonService.getList().get(index);
        int maHD = hd.getMaHoaDon();
        loadTableGioHang(hDCTService.timKiem(maHD));
        txt_tongtien.setText(String.valueOf(inHoaDon()));
        tb_giohang.setEnabled(true);
    }//GEN-LAST:event_tb_hoadonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_tienkhachdua.getText().isBlank() || !_Utilities.checkSoFloat(txt_tienkhachdua.getText())) {
            JOptionPane.showMessageDialog(this, "Phải nhập tiền khách đưa và nhập số");
            return;
        }
        if (Float.parseFloat(txt_tienkhachdua.getText()) < Float.parseFloat(txt_tongtien.getText())) {
            JOptionPane.showMessageDialog(this, "Còn thiếu " + (Float.parseFloat(txt_tongtien.getText()) - Float.parseFloat(txt_tienkhachdua.getText())) + " VND");
            return;
        }
        txt_tienthua.setText(String.valueOf(Float.parseFloat(txt_tienkhachdua.getText()) - Float.parseFloat(txt_tongtien.getText())));
        JOptionPane.showMessageDialog(this, hoaDonService.edit(guiDataThanhToan()));
        loadtableHoaDon(hoaDonService.getList());
        loadtableHoaDon1(hoaDonService.getListThanhToan());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb_giohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_giohangMouseClicked
        //    int index = tb_giohang.getSelectedRow();
        //    txt_tongtien.setText(tb_giohang.getModel().getValueAt(index, 5).toString());

    }//GEN-LAST:event_tb_giohangMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int indexSanPham = tb_sanPham.getSelectedRow();
        SanPham sp = sanPhamService.listSanPham().get(indexSanPham);
        int slsp = sp.getSoLuong();
//        String ma = sp.getMaSanPham();
//        String ten = sp.getTenSanPham();
//        Date namSX = sp.getNamSanXuat();
//        String hang = sp.getHangSanXuat();
//        float giaNhap = sp.getGiaNhap();
//        float giaBan = sp.getGiaBan();
//        float dungtich = sp.getDungTich();
//        String congsuat = sp.getCongSuat();
//        String pin = sp.getPin();
//        
        if (slsp < Integer.parseInt(txt_soluong.getText())) {
            JOptionPane.showMessageDialog(this, "Không đủ sản phẩm");
            return;
        }
        if (Integer.parseInt(txt_soluong.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Phải nhập số lượng > 0");
            return;
        }
        if(Integer.parseInt(txt_soluong.getText()) == 0){
            JOptionPane.showMessageDialog(this, "Không được nhập là 0");
            return;
        }
        if(Integer.parseInt(txt_soluong.getText()) > 0){
        sanPhamService.suaSanPham(new SanPhamView(sp.getMaSanPham(), sp.getTenSanPham(), slsp - Integer.parseInt(txt_soluong.getText()), sp.getNamSanXuat(), sp.getMauSac(),
                sp.getGiaNhap(), sp.getGiaBan(), sp.getDungTich(), sp.getCongSuat(), sp.getPin(),sp.getPhuKienDiKem(),sp.getBaoHanh(), sp.getMoTa(),sp.getTrangThai(), sp.getMaTheLoai(),sp.getMaHangSX() ));
        JOptionPane.showMessageDialog(this, hDCTService.add(guidataHDCT()));
        int index = tb_hoadon.getSelectedRow();
        HoaDon hd = hoaDonService.getList().get(index);
        int maHD = hd.getMaHoaDon();
        loadTableGioHang(hDCTService.timKiem(maHD));

        loadTableSanPham(sanPhamService.listSanPham());
        }
        txt_soluong.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimkiemActionPerformed
        loadTableSanPham(timKiem(txt_timkiem.getText()));
    }//GEN-LAST:event_btn_TimkiemActionPerformed

    private void tb_sanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sanPhamMouseClicked

    }//GEN-LAST:event_tb_sanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ThemKhachHangNhanh(user).setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdb_Gia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Gia1ActionPerformed
        loadTableSanPham(timKiemGia1());
    }//GEN-LAST:event_rdb_Gia1ActionPerformed

    private void rdb_Gia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Gia2ActionPerformed
        loadTableSanPham(timKiemGia2());
    }//GEN-LAST:event_rdb_Gia2ActionPerformed

    private void rdb_Gia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Gia3ActionPerformed
        loadTableSanPham(timKiemGia3());
    }//GEN-LAST:event_rdb_Gia3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        loadTableKhachHang(khachHangService.lishKH());
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        loadTableKhachHang(khachHangService.timKiem(txt_khachhang.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_traActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_traActionPerformed
        
        int indexx = tb_hoadon.getSelectedRow();
        HoaDon hd = hoaDonService.getList().get(indexx);
        int maHD = hd.getMaHoaDon();
        int index = tb_giohang.getSelectedRow();
        HDCT hdct = hDCTService.timKiem(maHD).get(index);
        int id = hdct.getSTT();
        int soluong = hdct.getSoLuong();
        String maSP = hdct.getMaSanPham().getMaSanPham();
        int indexSanPham = tb_sanPham.getSelectedRow();
        SanPham sp = sanPhamService.listSanPham().get(indexSanPham);
        int slsp = sp.getSoLuong();
        
      sanPhamService.suaSanPham(new SanPhamView(maSP, sp.getTenSanPham(), slsp + soluong, sp.getNamSanXuat(), sp.getMauSac(),
              sp.getGiaNhap(), sp.getGiaBan(), sp.getDungTich(), sp.getCongSuat(), sp.getPin(),sp.getPhuKienDiKem(),sp.getBaoHanh(), sp.getMoTa(),sp.getTrangThai(), sp.getMaTheLoai(),sp.getMaHangSX() ));
        JOptionPane.showMessageDialog(this, hDCTService.delete(id));
        loadTableGioHang(hDCTService.timKiem(maHD));
        loadTableSanPham(sanPhamService.listSanPham());
    }//GEN-LAST:event_btn_traActionPerformed

    private void tb_hoadon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hoadon1MouseClicked
       int index = tb_hoadon1.getSelectedRow();
        HoaDon hd = hoaDonService.getListThanhToan().get(index);
        int maHD = hd.getMaHoaDon();
        loadTableGioHang(hDCTService.timKiem(maHD));
        tb_giohang.setEnabled(false);
    }//GEN-LAST:event_tb_hoadon1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Timkiem;
    private javax.swing.JButton btn_taohoadon;
    private javax.swing.JButton btn_tra;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rdb_Gia1;
    private javax.swing.JRadioButton rdb_Gia2;
    private javax.swing.JRadioButton rdb_Gia3;
    private javax.swing.JTable tb_giohang;
    private javax.swing.JTable tb_hoadon;
    private javax.swing.JTable tb_hoadon1;
    private javax.swing.JTable tb_sanPham;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTextField txt_khachhang;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tienkhachdua;
    private javax.swing.JLabel txt_tienthua;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JLabel txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
