package Views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DomainModels.ChiTietSanPham;
import DomainModels.KichThuoc;
import DomainModels.ChatLieu;
import DomainModels.XuatXu;
import Helpers.DataValidator;
import Helpers.MessageDialogHelper;
import Repositories.ChiTietSanPhamRepository;
import Service.impl.QuanLyChiTietSanPhamService;
import Services.QuanLyChiTietSanPhamImpl;

import Utilities.DBConnection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hibernate.Session;

/**
 *
 * @author concu
 */
public class QLSanPham extends javax.swing.JPanel {

    private QuanLyChiTietSanPhamService quanLySanPhamService = new QuanLyChiTietSanPhamImpl();
    private QuanLyChiTietSanPhamImpl iml;
    private DefaultTableModel defaultTableModel;
    private DefaultComboBoxModel defaultComboBoxModel;

    private ChiTietSanPhamRepository spRepo = new ChiTietSanPhamRepository();

    /**
     * Creates new form QLSanPham
     */
    public QLSanPham() {
        initComponents();

        loadComboBoxXuatXu(quanLySanPhamService.getListXuatXu());
        loadComboBoxChatLieu(quanLySanPhamService.getListChatLieu());
        loadComboBoxKichThuoc(quanLySanPhamService.getListKichThuoc());

        loadTable(listSanPham());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTenGiay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbXuatXu = new javax.swing.JComboBox<>();
        cbSize = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cbChatLieu = new javax.swing.JComboBox<>();
        rbHoatDong = new javax.swing.JRadioButton();
        rbKhongHoatDong = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtMaGiay = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnThemXuatXu = new javax.swing.JButton();
        btnThemSize = new javax.swing.JButton();
        btnThemChatLieu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("(*)");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ SẢN PHẨM GiÀY");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(139, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(139, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(139, 20));

        btnThem.setBackground(new java.awt.Color(204, 0, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 0, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 0, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXem.setBackground(new java.awt.Color(204, 0, 255));
        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên giày:");

        jLabel4.setText("Xuất xứ:");

        jLabel3.setText("Giá:");

        jLabel7.setText("Số lượng:");

        jLabel11.setText("Size:");

        jLabel12.setText("Giảm giá:");

        jLabel5.setText("Chất liệu:");

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã giày", "Tên giày", "Xuất xứ", "Size", "Chất liệu", "Số lượng", "Giá", "Giảm giá", "Trạng thái"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        jLabel6.setText("Trạng thái:");

        buttonGroup1.add(rbHoatDong);
        rbHoatDong.setText("Hoạt động");

        buttonGroup1.add(rbKhongHoatDong);
        rbKhongHoatDong.setText("Không hoạt động");

        jLabel8.setText("Mã giày:");

        txtMaGiay.setBackground(new java.awt.Color(204, 204, 204));
        txtMaGiay.setForeground(new java.awt.Color(255, 255, 255));
        txtMaGiay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaGiay.setText("0");
        txtMaGiay.setDisabledTextColor(new java.awt.Color(255, 0, 102));
        txtMaGiay.setEnabled(false);

        btnThemXuatXu.setIcon(new javax.swing.ImageIcon("C:\\Users\\concu\\Downloads\\image\\plus.png")); // NOI18N
        btnThemXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXuatXuActionPerformed(evt);
            }
        });

        btnThemSize.setIcon(new javax.swing.ImageIcon("C:\\Users\\concu\\Downloads\\image\\plus.png")); // NOI18N
        btnThemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSizeActionPerformed(evt);
            }
        });

        btnThemChatLieu.setIcon(new javax.swing.ImageIcon("C:\\Users\\concu\\Downloads\\image\\plus.png")); // NOI18N
        btnThemChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChatLieuActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("(*)");

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("(*)");

        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("(*)");

        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("(*)");

        btnTimKiem.setText("Tìm kiếm:");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)))
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoLuong)
                            .addComponent(txtGia)
                            .addComponent(txtGiamGia)
                            .addComponent(txtTenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(37, 37, 37)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHoatDong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(rbKhongHoatDong))
                            .addComponent(cbXuatXu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbChatLieu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSize, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemXuatXu)
                            .addComponent(btnThemSize)
                            .addComponent(btnThemChatLieu))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(txtMaGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemXuatXu)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemSize)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemChatLieu)
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(rbHoatDong)
                        .addComponent(rbKhongHoatDong)
                        .addComponent(jLabel20))
                    .addComponent(btnXem))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void clear() {
        txtMaGiay.setText("");
        txtTenGiay.setText("");
        txtSoLuong.setText("");
        txtGia.setText("");
        txtGiamGia.setText("");
        rbHoatDong.setSelected(true);
    }

    public void fill() {
        int index = tbSanPham.getSelectedRow();
        ChiTietSanPham sp = listSanPham().get(index);
        String MaGiay = tbSanPham.getValueAt(index, 0).toString();

        String TenGiay = tbSanPham.getValueAt(index, 1).toString();

        String xuatXu = tbSanPham.getValueAt(index, 2).toString();

        String kichThuoc = tbSanPham.getValueAt(index, 3).toString();

        String ChatLieu = tbSanPham.getValueAt(index, 4).toString();

        String soLuong = tbSanPham.getValueAt(index, 5).toString();

        String gia = tbSanPham.getValueAt(index, 6).toString();

        String giamGia = tbSanPham.getValueAt(index, 7).toString();

        String TrangThai = tbSanPham.getValueAt(index, 8).toString();

        txtMaGiay.setText(MaGiay);
        txtTenGiay.setText(TenGiay);
        txtSoLuong.setText(soLuong);
        txtGia.setText(gia);
        txtGiamGia.setText(giamGia);
        if (TrangThai == "1") {
            rbHoatDong.isSelected();
        } else {
            rbKhongHoatDong.isSelected();
        }

        cbXuatXu.setSelectedItem(sp.getXuatXu().getMaXuatXu());
        cbSize.setSelectedItem(sp.getKichThuoc().getMaKichThuoc());
        cbChatLieu.setSelectedItem(sp.getChatLieu().getMaChatLieu());
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();

        DataValidator.vailidateEmpty(txtTenGiay, sb, "Tên giày không được để trống");
        DataValidator.vailidateEmpty(txtGia, sb, "Giá không được để trống");
        DataValidator.vailidateEmpty(txtSoLuong, sb, "Số lượng không được để trống");
        DataValidator.vailidateEmpty(txtGiamGia, sb, "Giảm giá không được để trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }

        ChiTietSanPham ctsp = new ChiTietSanPham();

        String tenSP = txtTenGiay.getText();

        String soLuong = txtSoLuong.getText();
        Integer soLuongStr = Integer.parseInt(soLuong);

        String gia = this.txtGia.getText();
        Double giaS = Double.parseDouble(gia);
        BigDecimal giaStr = BigDecimal.valueOf(giaS);

        String giamGia = txtGiamGia.getText();
        Double giamGiaS = Double.parseDouble(giamGia);
        BigDecimal giamgiaStr = BigDecimal.valueOf(giamGiaS);

        XuatXu xuatXu = (XuatXu) cbXuatXu.getSelectedItem();
        ctsp.setXuatXu(xuatXu);

        KichThuoc kichThuoc = (KichThuoc) cbSize.getSelectedItem();
        ctsp.setKichThuoc(kichThuoc);

        ChatLieu chatLieu = (ChatLieu) cbChatLieu.getSelectedItem();
        ctsp.setChatLieu(chatLieu);

        ctsp.setTrangThai(rbHoatDong.isSelected() ? 1 : 0);

        ctsp.setTenCTSP(tenSP);
        ctsp.setSoLuong(soLuongStr);
        ctsp.setGia(giaStr);
        ctsp.setGiamGia(giamgiaStr);

        try {

            if (Double.valueOf(gia) < 0) {
                JOptionPane.showMessageDialog(this, "Không được được để âm");
                this.txtGia.setText("");

            } else if (Double.valueOf(soLuongStr) < 0) {
                JOptionPane.showMessageDialog(this, "Không được được để âm");
                this.txtSoLuong.setText("");

            } else if (Double.valueOf(giamGia) < 0) {
                JOptionPane.showMessageDialog(this, "Không được được để âm");
                this.txtGiamGia.setText("");
            } else {
                int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thêm không", "Xác nhận", JOptionPane.YES_NO_OPTION);

                if (xacNhan == JOptionPane.YES_OPTION) {
                    String result = quanLySanPhamService.addCTSanPham(ctsp);
                    JOptionPane.showMessageDialog(this, result);
                    loadTable(quanLySanPhamService.getListChiTietSanPham());
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không đúng định dạng");
            this.txtSoLuong.setText("");
            this.txtGia.setText("");
            this.txtGiamGia.setText("");
            this.txtTenGiay.setText("");
        }


    }//GEN-LAST:event_btnThemActionPerformed


    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        StringBuilder sb = new StringBuilder();

        DataValidator.vailidateEmpty(txtTenGiay, sb, "Tên giày không được để trống");
        DataValidator.vailidateEmpty(txtGia, sb, "Giá không được để trống");
        DataValidator.vailidateEmpty(txtSoLuong, sb, "Số lượng không được để trống");
        DataValidator.vailidateEmpty(txtGiamGia, sb, "Giảm giá không được để trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }

        ChiTietSanPham ctsp = new ChiTietSanPham();

        String tenSP = txtTenGiay.getText();

        String soLuong = txtSoLuong.getText();
        Integer soLuongStr = Integer.parseInt(soLuong);

        String gia = this.txtGia.getText();
        Double giaS = Double.parseDouble(gia);
        BigDecimal giaStr = BigDecimal.valueOf(giaS);

        String giamGia = txtGiamGia.getText();
        Double giamGiaS = Double.parseDouble(giamGia);
        BigDecimal giamgiaStr = BigDecimal.valueOf(giamGiaS);

        XuatXu xuatXu = (XuatXu) cbXuatXu.getSelectedItem();
        ctsp.setXuatXu(xuatXu);

        KichThuoc kichThuoc = (KichThuoc) cbSize.getSelectedItem();
        ctsp.setKichThuoc(kichThuoc);

        ChatLieu chatLieu = (ChatLieu) cbChatLieu.getSelectedItem();
        ctsp.setChatLieu(chatLieu);

        ctsp.setTrangThai(rbHoatDong.isSelected() ? 1 : 0);

        ctsp.setTenCTSP(tenSP);
        ctsp.setSoLuong(soLuongStr);
        ctsp.setGia(giaStr);
        ctsp.setGiamGia(giamgiaStr);

        try {

            if (Double.valueOf(gia) < 0) {
                JOptionPane.showMessageDialog(this, "Không được được để âm");
                this.txtGia.setText("");

            } else if (Double.valueOf(soLuongStr) < 0) {
                JOptionPane.showMessageDialog(this, "Không được được để âm");
                this.txtSoLuong.setText("");

            } else if (Double.valueOf(giamGia) < 0) {
                JOptionPane.showMessageDialog(this, "Không được được để âm");
                this.txtGiamGia.setText("");
            } else {
                int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa không", "Xác nhận", JOptionPane.YES_NO_OPTION);

                if (xacNhan == JOptionPane.YES_OPTION) {
                    String result = quanLySanPhamService.updateCTSanPham(ctsp);
                    JOptionPane.showMessageDialog(this, result);
                    loadTable(quanLySanPhamService.getListChiTietSanPham());
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không đúng định dạng");
            this.txtSoLuong.setText("");
            this.txtGia.setText("");
            this.txtGiamGia.setText("");
            this.txtTenGiay.setText("");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        try {
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa không", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (xacNhan == JOptionPane.YES_OPTION) {
                // TODO add your handling code here:
                int index = tbSanPham.getSelectedRow();
                String ma = tbSanPham.getValueAt(index, 0).toString();
                quanLySanPhamService.XoaSanPham(Integer.parseInt(txtMaGiay.getText()));
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadTable(quanLySanPhamService.getListChiTietSanPham());

            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }

        } catch (SQLException ex) {
            Logger.getLogger(QLSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        fill();

    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemActionPerformed
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        iml = new QuanLyChiTietSanPhamImpl();
        if (txtTimKiem.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sản phẩm");
            return;
        }
        timKiem((ArrayList<ChiTietSanPham>) iml.timKiem(txtTimKiem.getText()));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXuatXuActionPerformed
        XuatXuJpanel xx = new XuatXuJpanel();
        xx.setVisible(true);
    }//GEN-LAST:event_btnThemXuatXuActionPerformed

    private void btnThemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSizeActionPerformed
        KichThuocJpanel kt = new KichThuocJpanel();
        kt.setVisible(true);
    }//GEN-LAST:event_btnThemSizeActionPerformed

    private void btnThemChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChatLieuActionPerformed

        ChatLieuJPanel cl = new ChatLieuJPanel();
        cl.setVisible(true);
    }//GEN-LAST:event_btnThemChatLieuActionPerformed

    public ArrayList<ChiTietSanPham> listSanPham() {
        return quanLySanPhamService.getListChiTietSanPham();
    }

    private void timKiem(ArrayList<ChiTietSanPham> list) {
        defaultTableModel = (DefaultTableModel) tbSanPham.getModel();
        defaultTableModel.setRowCount(0);
        for (ChiTietSanPham ctsp : list) {
            if (ctsp.getMaCTSP().equals(txtTimKiem.getText()) || ctsp.getTenCTSP().equals(txtTimKiem.getText())) {
                defaultTableModel.addRow(new Object[]{
                    ctsp.getMaCTSP(), ctsp.getTenCTSP(), ctsp.getXuatXu(), ctsp.getKichThuoc(),
                    ctsp.getChatLieu(), ctsp.getSoLuong(), ctsp.getGia(), ctsp.getGiamGia(), ctsp.getTrangThai() == 1 ? "Hoạt động" : "Không hoạt động",});
            }
        }

    }

    private void loadTable(ArrayList<ChiTietSanPham> list) {
        defaultTableModel = (DefaultTableModel) tbSanPham.getModel();
        defaultTableModel.setRowCount(0);
        for (ChiTietSanPham ctsp : list) {
            defaultTableModel.addRow(new Object[]{
                ctsp.getMaCTSP(), ctsp.getTenCTSP(), ctsp.getXuatXu(), ctsp.getKichThuoc(),
                ctsp.getChatLieu(), ctsp.getSoLuong(), ctsp.getGia(), ctsp.getGiamGia(), ctsp.getTrangThai() == 1 ? "Hoạt động" : "Không hoạt động",});
        }

    }

    private void loadComboBoxXuatXu(ArrayList<XuatXu> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbXuatXu.getModel();
        for (XuatXu xuatXu : list) {
            defaultComboBoxModel.addElement(xuatXu);

        }

    }

    private void loadComboBoxChatLieu(ArrayList<ChatLieu> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbChatLieu.getModel();
        for (ChatLieu chatLieu : list) {
            defaultComboBoxModel.addElement(chatLieu);

        }

    }

    private void loadComboBoxKichThuoc(ArrayList<KichThuoc> list) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbSize.getModel();
        for (KichThuoc kichThuoc : list) {
            defaultComboBoxModel.addElement(kichThuoc);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemChatLieu;
    private javax.swing.JButton btnThemSize;
    private javax.swing.JButton btnThemXuatXu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbChatLieu;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JComboBox<String> cbXuatXu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rbHoatDong;
    private javax.swing.JRadioButton rbKhongHoatDong;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaGiay;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenGiay;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
